import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useAuth } from '../context'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { login, logout, currentUser } = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Nextjs + Firebase 9
        </h1>

        <div className='shadow p-5 w-2/6'>
          {
            currentUser && (
              <div className=' flex items-center justify-between'>
                <h2>{currentUser?.displayName}</h2>
                <Image
                  alt='Avatar'
                  className=' rounded'
                  src={currentUser.photoURL as string}
                  width={68}
                  height={68}
                />
              </div>
            )
          }
          <div>
            {
              !currentUser && <button className=' px-3 py-2 rounded bg-gray-100' onClick={login}>
                Login
              </button>
            }

            {
              currentUser && <button className=' px-3 py-2 rounded bg-gray-100' onClick={logout}>
                Logout
              </button>
            }
          </div>
        </div>
      </main >

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}

export default Home
